### ISSUE TITLE
Extend to .ics files?

### ISSUE THREAD

**Issue by githubtefo** [fcusr/dynamic-calendar-and-clocks-icons#1]
Hi there,

Great extension! Would be nice to see event's dates on .ics files (similar to Mac OS).

**Comment by fcusr** [comment]
I don't use Mac OS, can you give a more detailed description about this feature?
It seems that the Mac OS calendar icon just shows the current date, not event's dates.

**Comment by fcusr** [comment]
File thumbnails are generated by nautilus. This cannot be implemented by a shell extension.

**Comment by maxxcan** [comment]
Hello. 

I love this extension. Do you think to do the same with the weather icon? I think do for myself buy maybe You do faster

**Comment by fcusr** [comment]
I will add support for weather icon in later versions.
