### ISSUE TITLE
Bug: weather icon not shown

### ISSUE THREAD

**Issue by dschier-wtd** [fcusr/dynamic-calendar-and-clocks-icons#3]
Hi, I am currently on Fedora 37 and using GNOME Weather as flatpak from flathub. Calendar and Clocks are working awesome with the same setup.
For the weather icon, it seems like some icon is not found and a "?" is presented instead.

![image](https://user-images.githubusercontent.com/6490538/205503513-29acc244-569b-4ccf-87bc-a2af0f8bd163.png)

Please feel free to reach out to me for further diagnostics and debug help.

**Comment by fcusr** [comment]
Fixed in the latest version.

**Comment by dschier-wtd** [comment]
Yay, that was quick. Thanks a lot!
