### ISSUE TITLE
Gnome 45 support

### ISSUE THREAD

**Issue by sidevesh** [fcusr/dynamic-calendar-and-clocks-icons#9]
The Calendar icon has also changed so that will need to be updated too.

**Comment by prstephens** [comment]
I agree. I love this extension. makes my MacOS theme complete. lets hope the developer is still active.

**Comment by stpnwf** [comment]
Is support planned?

**Comment by prstephens** [comment]
no one knows. its all gone a bit quiet :(

**Comment by johannesjh** [comment]
I just found that commit 775d513a294ccb7995d2bcd5a8e98bdf929d2740 introduced compatibililty with gnome45... thank you @fcusr for this wonderful extension! 

I installed the extension by copying the `dynamic-calendar-and-clocks-icons@fcusr.github.com` folder from this repository into `~/.local/share/gnome-shell/extensions/`. I logged out and logged back in. I could then enable the extension using the "extension manager" app.
